### ISSUE TITLE
Feature-request: count

### ISSUE THREAD

**Issue by windisch** [dkahle/algstat#1]
Hi,

would it be possible to extend the functionality of `count` so that it takes matrices `A` and right-hand sides `b` as arguments? That is, that something like

``` r
A=matrix(c(1,1,1,1),1,4);
b=c(10);
count(A,b);
```

is possible, where `count(A,b)` is the number of integer points in the `b`-fiber of `A`, i.e., all non-negative integer solutions `u` of `Au=b`? 

Alternatively, it would also be fine if there would be a method which transforms the set of equations `Ax=b, x>=0` into the form demanded by the specifications of count (for the example above: `"x1+x2+x3=10","x1>=0","x2>=0","x3>=0"`).

Thanks!
Tobias

**Comment by dkahle** [comment]
Got it, thanks!
